// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jldedgikvduhjjvlyygv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpsZGVkZ2lrdmR1aGpqdmx5eWd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MDI0NTAsImV4cCI6MjA3MTI3ODQ1MH0.8PiUxiXIJWXIbTn120JxX27gLf_hq32KfWV_AahkUQo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});